contribution:
  - changed-files:
      - any-glob-to-any-file:
          - "submissions/examples/**"
          - "submissions/docs/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "submissions/docs/**"

core:
  - changed-files:
      - any-glob-to-any-file:
          - "core/**"